version: '3.9'

networks:
  iced-latte-network:
    name: iced-latte-network
    external: false

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
  nginx_conf:

services:
  iced-latte-backend:
    image: 'zufarexplainedit/iced-latte-backend:latest'
    container_name: iced-latte-backend
    environment:
      APP_SERVER_PORT: 8083
      APP_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      DATASOURCE_PORT: 5432
      DATASOURCE_NAME: testdb
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_HOST: iced-latte-postgresdb
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '8083:8083'
    networks:
      - iced-latte-network
    depends_on:
      - iced-latte-postgresdb
    restart: on-failure

  iced-latte-postgresdb:
    image: 'postgres:13.11-bullseye'
    container_name: iced-latte-postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    networks:
      - iced-latte-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  iced-latte-prometheus:
    image: prom/prometheus:v2.33.3
    container_name: iced-latte-prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - iced-latte-network
    restart: on-failure

  iced-latte-grafana:
    image: grafana/grafana:9.1.5
    container_name: iced-latte-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      - iced-latte-network
    depends_on:
      - iced-latte-prometheus
    restart: on-failure

  iced-latte-nginx:
    image: nginx:alpine
    container_name: iced-latte-nginx
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    networks:
      - iced-latte-network
    depends_on:
      - iced-latte-backend
      - iced-latte-prometheus
      - iced-latte-grafana
    restart: on-failure

  iced-latte-redis:
    image: redis/redis-stack:latest
    container_name: iced-latte-redis
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6380
    ports:
      - "6380:6380"