openapi: "3.0.3"

info:
  title: "Iced Latte Rating API"
  description: "API allows users to add ratings to products."
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://iced-latte.uk/backend"
    description: "Production server"

tags:
  - name: "ProductRating"
    description: "Operations related to rating products"

paths:
  /api/v1/products/{productId}/ratings/{rating}:
    post:
      tags:
        - "ProductRating"
      summary: "Add rating to product"
      operationId: "addNewProductRating"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of the product to get rating for"
          required: true
          schema:
           type: "string"
           format: "uuid"
        - name: "rating"
          in: "path"
          description: "Rating value"
          required: true
          schema:
            type: "integer"
            minimum: 1
            maximum: 5
      responses:
        "200":
          description: "Rating added successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductRatingDto"

  /api/v1/products/{productId}/ratings:
    get:
      tags:
        - "ProductRating"
      summary: "Get Product Rating"
      operationId: "getRatingByProductId"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of the product to get rating for"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Product rating retrieved successfully."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ProductRating"

components:
  schemas:
    ProductRatingDto:
      type: object
      properties:
        productId:
          type: string
          format: "uuid"
        rating:
          type: Integer
      required:
        - productId
        - rating

    ProductRating:
      type: object
      properties:
        rating:
          type: Integer
        quantity:
          type: Integer
      required:
        - rating
        - quantity