openapi: "3.0.3"
info:
  title: "Iced Latte Shipping API"
  description: "API allows users to manage their shipping, including adding, updating, and deleting shipping info. It includes detailed error responses and provides examples for better understanding."
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://dev.api.it-sl.ru"
    description: "Production server"

tags:
  - name: "Shipping"
    description: "Operations related to shipping"

paths:
  /api/v1/shipping/{shippingId}:
    get:
      tags:
        - "Shipping"
      summary: "Get shipping information by ID"
      operationId: "getShippingById"
      parameters:
        - name: "shippingId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "Successful response with the details of the shipping information"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShippingInfoDto'
        "404":
          description: "Shipping information not found"

    delete:
      tags:
        - "Shipping"
      summary: "Delete a shipping entry by ID"
      operationId: "deleteShippingById"
      parameters:
        - name: "shippingId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "Shipping entry deleted successfully"
        "404":
          description: "Shipping information not found"

  /api/v1/shipping:
    post:
      tags:
        - "Shipping"
      summary: "Create a new shipping entry"
      operationId: "createShipping"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShippingInfoDto'
      responses:
        "201":
          description: "Shipping entry created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShippingInfoDto'
        "400":
          description: "Invalid input"

  /api/v1/shipping/user/{userId}:
    get:
      tags:
        - "Shipping"
      summary: "Get all shipping information for a specific user"
      operationId: "getAllShippingByUserId"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
          description: "Unique identifier of the user"
      responses:
        "200":
          description: "Successful response with a list of shipping information for the user"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/ShippingInfoDto'
        "404":
          description: "User not found or no shipping information available"

components:
  schemas:
    ShippingInfoDto:
      type: object
      required:
        - shippingUserEmail
        - shippingUserFirstName
        - shippingUserLastName
        - shippingUserPhoneNumber
        - shippingMethod
      properties:
        shippingUserEmail:
          type: string
          format: email
          description: "Email address of the user for shipping."
        shippingUserFirstName:
          type: string
          description: "First name of the user for shipping."
        shippingUserLastName:
          type: string
          description: "Last name of the user for shipping."
        shippingUserPhoneNumber:
          type: "string"
          pattern: "^\\+?[1-9]\\d{1,14}$"
          description: "The international phone number of the recipient."
        shippingMethod:
          type: string
          description: "Method of shipping."
        address:
          $ref: "#/components/schemas/ShippingAddressDto"

    ShippingAddressDto:
      type: object
      properties:
        country:
          type: string
          description: "Country in the shipping address."
        addressLine:
          type: string
          description: "Address line in the shipping address."
        city:
          type: string
          description: "City in the shipping address."
        zipCode:
          type: string
          description: "Zip code in the shipping address."
