name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build-and-push-docker-image:
    name: Build and push a new docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code from the Github repository
        uses: actions/checkout@v4

      - name: Set DOCKER_IMAGE_TAG
        run: echo "DOCKER_IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ACCOUNT_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag a new docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_ACCOUNT_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .

      - name: Push a new docker image into Dockerhub
        run: docker push ${{ secrets.DOCKER_HUB_ACCOUNT_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

  deploy-app-to-server:
    name: Deploy application to remote server via SSH
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Set DOCKER_IMAGE_TAG
        run: echo "DOCKER_IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Deploy image via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIV_KEY }}
          script: |
            docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker rmi ${{ secrets.DOCKER_HUB_ACCOUNT_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }} || true
            docker pull ${{ secrets.DOCKER_HUB_ACCOUNT_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
            docker run -d \
              --name ${{ secrets.DOCKER_CONTAINER_NAME }} \
              --network=${{ secrets.DOCKER_NETWORK }} \
              -e APP_SERVER_PORT=${{ secrets.APP_SERVER_PORT }} \
              -e DATASOURCE_PORT=${{ secrets.DATASOURCE_PORT }} \
              -e DATASOURCE_NAME=${{ secrets.DATASOURCE_NAME }} \
              -e DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
              -e DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
              -e DATASOURCE_HOST=${{ secrets.DATASOURCE_HOST }} \
              -e APP_JWT_SECRET=${{ secrets.APP_JWT_SECRET }} \
              -e APP_JWT_REFRESH_SECRET=${{ secrets.APP_JWT_REFRESH_SECRET }} \
              -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
              -e AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
              -e AWS_REGION=${{ secrets.AWS_REGION }} \
              -e AWS_USER_BUCKET=${{ secrets.AWS_USER_BUCKET }} \
              -e AWS_PRODUCT_BUCKET=${{ secrets.AWS_PRODUCT_BUCKET }} \
              -e AWS_DEFAULT_PRODUCT_IMAGES_PATH=${{ secrets.AWS_DEFAULT_PRODUCT_IMAGES_PATH }} \
              -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
              -v ${{ secrets.APP_DATA_PATH_ON_THE_REMOTE_SERVER }}:/usr/app/logs \
              -v ${{ secrets.APP_DATA_PATH_ON_THE_REMOTE_SERVER }}/products:/usr/app/products \
              ${{ secrets.DOCKER_HUB_ACCOUNT_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
